services:
    npm:
        container_name: npm
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "127.0.0.1:81:81"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
        environment:
            PUID: 1000
            PGID: 1000
            DISABLE_IPV6: "true"

networks:
    default:
        name: npm
